export const registerContainer: string;
export const registerForm: string;
export const appLogo: string;
export const registerButton: string;
export const redirectLoginButton: string;
export const registerElement: string;
export const focus: string;
export const hover: string;
export const errorMessageContainer: string;
