export const registerContainer: string;
export const appLogo: string;
export const registerForm: string;
export const registerElementContainer: string;
export const registerElement: string;
export const focus: string;
export const loginIcon: string;
export const resendEmail: string;
export const errorMessageContainer: string;
