export const loginContainer: string;
export const appLogo: string;
export const loginForm: string;
export const loginElementContainer: string;
export const loginElement: string;
export const focus: string;
export const loginIcon: string;
export const register: string;
export const errorMessageContainer: string;
