FROM microsoft/aspnetcore-build:1.1.2

COPY . /app
WORKDIR /app

RUN ["dotnet", "restore"]
RUN ["npm", "install"]
RUN ["dotnet", "build"]

EXPOSE 5000/tcp
ENV ASPNETCORE_URLS http://*:5000
ENV ASPNETCORE_ENVIRONMENT="Development"

ENTRYPOINT ["dotnet", "run"]