# Sample contents of Dockerfile
# Stage 1
FROM microsoft/aspnetcore-build:1.1.2 AS builder
WORKDIR /source

# caches restore result by copying csproj file separately
COPY *.csproj .
RUN dotnet restore

# copies the rest of your code
COPY . .
RUN dotnet publish --output /app/ --configuration Release

# Stage 2
# This container does not have any node modules nor dotnet dependencies
FROM microsoft/aspnetcore-build:1.1.2

WORKDIR /app
COPY --from=builder /app .
EXPOSE 5000/tcp

ENTRYPOINT ["dotnet", "app.dll"]