# Sample contents of Dockerfile
# Stage 1
FROM microsoft/aspnetcore-build:1.1.2 AS builder
WORKDIR /source

# caches restore result by copying csproj file separately
COPY *.csproj .
RUN dotnet restore

# copies the rest of your code
COPY . .
RUN dotnet publish --output /app/ --configuration Release

# Stage 2
FROM microsoft/aspnetcore
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -
RUN apt-get install -y build-essential nodejs
WORKDIR /app
COPY --from=builder /app .
EXPOSE 5000/tcp
ENV ASPNETCORE_URLS http://*:5000
ENTRYPOINT ["dotnet", "app.dll"]