export const loginContainer: string;
export const loginForm: string;
export const loading: string;
export const loginButton: string;
export const registerRedirectButton: string;
export const loginElement: string;
export const focus: string;
export const hover: string;
export const errorMessageContainer: string;
